name: 02 - Workflow Events

on: 
    push:
    pull_request:
    workflow_dispatch:
    schedule:
        - cron: '0 * * * *'

#Let's add a comment here
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: |
                echo "Event name: ${{github.event_name}}"